config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "registrations"}
  get 'pages/landing'
	get 'pages/landing2'
  get 'projects/show/:id', to: 'projects#show', as: 'projects'
  get 'projects/index'
  get 'projects/new'
	post 'projects/create'
	post 'projects/update'
	post 'posts/create'
	post 'comments/create'
	post 'subscriptions/create'
	post 'stripe_infos/create'
	post 'stripe_infos/add_bank_account'
	post 'stripe_infos/remove_bank_account', to: 'stripe_infos#remove_bank_account', as: 'stripe_infos_remove_bank_account'
	post 'stripe_infos/default_bank_account', to: 'stripe_infos#default_bank_account', as: 'stripe_infos_default_bank_account'
	post 'stripe_infos/create_payout', to: 'stripe_infos#create_payout', as: 'stripe_infos_create_payout'
	post 'stripe_infos/submit_fields_needed', to: 'stripe_infos#submit_fields_needed', as: 'stripe_infos_submit_fields_needed'
	post 'stripe/webhooks', to: 'stripe_infos#stripe_webhooks', as: 'stripe_wehbooks'
	post 'releases/create'
	post 'rss_s3s/create'
	delete 'subscriptions/destroy/:id', to: 'subscriptions#destroy', as: 'subscriptions_destroy'
	get 'projects/dashboard/:id', to: 'projects#dashboard', as: 'dashboard'
	root to: 'pages#landing2'
	get '/:slug', to: 'projects#show', as: 'projects_slug'
	get 'settings/withdraw/:id', to: 'settings#withdraw', as: 'withdraw'
	get 'users/show/:id', to: 'users#show', as: 'user_show'
	get 'projects/edit/:slug', to: 'projects#edit', as: 'edit_project'
	get 'rss_s3s/:hashid', to: 'rss_s3s#show', as: 'rss_s3'
	get 'rss_feeds/:hashid', to: 'rss_feeds#show', as: 'rss_feed', format: 'rss'

	resources :charges

end

app/views/shared/_footer.html.erb
<div class="footer-container w-container">
  <div class="w-row">
    <div class="w-col w-col-8">
      <div class="w-row">
        <div class="w-col w-col-3">
          <h4 class="footer-home-title">Groundwork</h4>
          <p class="footer-copyright">&copy; <%= Time.current.year %></p>
        </div>
        <div class="w-col w-col-3">
          <h5 class="footer-h5">Sitemap</h5>
					<a class="footer-link" href="/">Home</a>
					<a class="footer-link" href="#">About us</a>
					<a class="footer-link" href="/projects/index">Browse</a>
					<% if user_signed_in? %>
						<%= link_to('Sign out', destroy_user_session_path, :method => :delete, class: 'footer-link') %>
					<% else %>
						<a class="footer-link" data-ix="signup-button" href="#">Sign up</a>
						<a class="footer-link" data-ix="login-button" href="#">Sign in</a>
					<% end %>
        </div>
        <div class="w-col w-col-3"></div>
        <div class="w-col w-col-3"></div>
      </div>
    </div>
    <div class="w-col w-col-4">
      <h5 class="footer-h5">Connect</h5>
			<a class="footer-link" href="#">Mail <i class="fa fa-envelope" aria-hidden="true"></i></a>
			<a class="footer-link" href="#">Twitter <i class="fa fa-twitter" aria-hidden="true"></i></a>
    </div>
  </div>
</div>

app/views/shared/_login_modal.html.erb
<div class="login-modal" data-ix="login-modal">
	<div class="login-wrapper"><a class="login-close"><strong class="login-close-button" data-ix="login-modal-close">X</strong></a>
		<h3 class="login-modal-title">Sign in</h3>
		<p>Please enter your email and password to sign in.</p>
		<div class="w-form">
			<%= form_for('user', data: {name: "Email Form"}, html: {id: "email-form", name: "email-form"}, url: user_session_path ) do |f| %>
				<label class="form-label" for="Email-2">Login</label>
				<%= f.email_field :login, data: {name: 'login'}, class: "w-input", id: "login", maxlength: "256", placeholder: "Login", required: "required", type:"login", autofocus: 'true' %>

				<label class="form-label" for="password-2">Password</label>
				<%= f.password_field :password, data: {name: 'password'}, class: "w-input", id: "password", maxlength: "256", placeholder: "Password", required: "required", type:"password" %>

				<%= f.submit "Sign in", class: 'login-button w-button', data: {wait: 'Please wait...'} %>
			<% end %>
			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_nav.html.erb
<div class="nav-bar w-nav" data-animation="default" data-collapse="medium" data-duration="400">
	<%= link_to('MyGroundworks [beta]', root_path, class: 'nav-home-link w-nav-link') %>
	<div class="nav-container w-container">
		<nav class="nav-menu w-nav-menu" role="navigation">
			<% if user_signed_in? %>
				<%= link_to('My Profile', user_show_path(current_user.id), class: 'w-nav-link') %>
				<%= link_to('Sign out', destroy_user_session_path, :method => :delete, class: 'w-nav-link') %>
			<% else %>
				<a class="w-nav-link" data-ix="signup-button" href="#">Get Started</a>
				<a class="w-nav-link" data-ix="signup-button" href="#">Sign up</a>
				<a class="w-nav-link" data-ix="login-button" href="#">Sign in</a>
			<% end %>
			<a class="w-nav-link" href="/projects/index">Browse</a>
			<a class="landing-nav-link w-nav-link">
				<%= form_tag(projects_index_path(), :method => "get", class: "search-form", enforce_utf8: false) do %>
						<%= text_field_tag :search, params[:search], placeholder: "Search Projects", class: "search-text-field" %>
						<%= submit_tag "Search", :name => nil, class: "search-button" %>
				<% end %>
			</a>
			<a class="nav-start-button w-button" href="/projects/new">Start a Project</a>
		</nav>
		<div class="w-nav-button">
			<div class="w-icon-nav-menu"></div>
		</div>
	</div>
</div>

app/views/shared/_nav_landing.html.erb
<div class="landing nav-bar w-nav" data-animation="default" data-collapse="medium" data-duration="400">
	<%= link_to('MyGroundworks [beta]', root_path, class: 'nav-home-link landing-nav-link w-nav-link') %>
	<div class="nav-container w-container">
		<nav class="nav-menu w-nav-menu" role="navigation">
			<% if user_signed_in? %>
				<%= link_to('My Profile', user_show_path(current_user.id), class: 'w-nav-link') %>
			  <%= link_to('Sign out', destroy_user_session_path, :method => :delete, class: 'landing-nav-link w-nav-link') %>
			<% else %>
				<a class="landing-nav-link w-nav-link" data-ix="signup-button" href="#">Get Started</a>
				<a class="landing-nav-link w-nav-link" data-ix="signup-button" href="#">Sign up</a>
				<a class="landing-nav-link w-nav-link" data-ix="login-button" href="#">Sign in</a>
			<% end %>
			<a class="landing-nav-link w-nav-link" href="/projects/index">Browse</a>
			<a class="landing-nav-link w-nav-link">
				<%= form_tag(projects_index_path, :method => "get", class: "search-form", enforce_utf8: false) do %>
				    <%= text_field_tag :search, params[:search], placeholder: "Search Projects", class: "search-text-field" %>
				    <%= submit_tag "Search", :name => nil, class: "search-button" %>
				<% end %>
			</a>
			<a class="nav-start-button w-button" href="/projects/new">Start a Project</a>
		</nav>
		<div class="w-nav-button">
			<div class="w-icon-nav-menu"></div>
		</div>
	</div>
</div>

app/views/shared/_signup_modal.html.erb
<div class="signup-modal" data-ix="signup-modal">
	<div class="signup-wrapper"><a class="signup-close"><strong class="signup-close-button" data-ix="signin-modal">X</strong></a>
		<h3 class="signup-modal-title">Sign up</h3>
		<p>Please enter your email and password to sign up.</p>
		<div class="w-form">
			<%= form_for('user', data: {name: "Email Form"}, html: {id: "email-form", name: "email-form"}, url: user_registration_path ) do |f| %>
				<label class="form-label" for="email">Email</label>
				<%= f.email_field :email, data: {name: 'email'}, class: "w-input", id: "email", maxlength: "256", placeholder: "Email", required: "required", type:"email", autofocus: 'true' %>

				<label class="form-label" for="username">Username</label>
				<%= f.email_field :username, data: {name: 'username'}, class: "w-input", id: "username", maxlength: "256", placeholder: "Username", required: "required", type:"username", autofocus: 'true' %>

				<label class="form-label" for="password">Password</label>
		    <%= f.password_field :password, data: {name: 'password'}, class: "w-input", id: "password", maxlength: "256", placeholder: "Password", required: "required", type:"password" %>

				<label class="form-label" for="password_confirmation">Confirm Password</label>
				<%= f.password_field :password_confirmation, data: {name: 'password_confirmation'}, class: "w-input", id: "password_confirmation", maxlength: "256", placeholder: "Password", required: "required", type:"password" %>

				<label class="form-label" for="username">Country</label>
				<%= f.collection_select :country_id, Country.order(:name), :id, :name, {}, { class: "w-input", required: "required" } %>

				<label class="form-label" for="tos">Terms of Service</label>
				<div style="text-align:left;">
					<%= check_box :tos, {}, { required: "required" } %>
					<p style="display:inline-block;">By registering your account, you agree to our Services Agreement and the <a href="https://stripe.com/connect-account/legal">Stripe Connected Account Agreement.</a></p>
				</div>

				<%= recaptcha_tags %>

			  <%= f.submit "Sign up", class: 'login-button w-button', data: {wait: 'Please wait...'}, onclick: 'fbq("track", "CompleteRegistration");' %>
			<% end %>
			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_subscribe.html.erb
<div class="subscribe-modal" data-ix="subscribe-modal">
	<div class="subscribe-wrapper">
		<a class="subscribe-close">
			<strong class="subscribe-close-button" data-ix="subscribe-modal-close">X</strong>
		</a>
		<h3 class="subscribe-modal-title">Subscribe</h3>
		<p>Please enter your email and password to sign in.</p>
		<div class="w-form">
			<%= form_for('subscription', data: {name: "subscription Form"}, html: {id: "subscription-form", name: "subscription-form"}, url: subscription_path ) do |f| %>
				<%= f.hidden_field :user_id, value: current_user.id %>
				<%= f.hidden_field :project_id, value: @project.id %>
				<%= f.hidden_field :type, :value => @project.format %>
				<label class="form-label" for="tier">Tier</label>
				<%= collection_select(:project, :rewards_tiers_id, @project.rewards_tiers.all, :id, :title, prompt: true, data: {name: 'login'}, class: "w-input", id: "login", maxlength: "256", placeholder: "Login", required: "required", type:"login", autofocus: 'true') %>

				<label class="form-label" for="amount">Amount</label>
				<%= f.text_field :amount, data: {name: 'amount'}, class: "w-input", id: "amount", maxlength: "256", placeholder: "$1", required: "required" %>

				<%= f.submit "Subscribe", class: 'subscribe-button w-button', data: {wait: 'Please wait...'} %>
			<% end %>
			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>