config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "registrations"}
  get 'pages/landing'
	get 'pages/landing2'
  get 'projects/show/:id', to: 'projects#show', as: 'projects'
  get 'projects/index'
  get 'projects/new'
	post 'projects/create'
	post 'projects/update'
	post 'posts/create'
	post 'comments/create'
	post 'subscriptions/create'
	post 'stripe_infos/create'
	post 'stripe_infos/add_bank_account'
	post 'stripe_infos/remove_bank_account', to: 'stripe_infos#remove_bank_account', as: 'stripe_infos_remove_bank_account'
	post 'stripe_infos/default_bank_account', to: 'stripe_infos#default_bank_account', as: 'stripe_infos_default_bank_account'
	post 'stripe_infos/create_payout', to: 'stripe_infos#create_payout', as: 'stripe_infos_create_payout'
	post 'stripe_infos/submit_fields_needed', to: 'stripe_infos#submit_fields_needed', as: 'stripe_infos_submit_fields_needed'
	post 'stripe/webhooks', to: 'stripe_infos#stripe_webhooks', as: 'stripe_wehbooks'
	post 'releases/create'
	post 'rss_s3s/create'
	delete 'subscriptions/destroy/:id', to: 'subscriptions#destroy', as: 'subscriptions_destroy'
	get 'projects/dashboard/:id', to: 'projects#dashboard', as: 'dashboard'
	root to: 'pages#landing2'
	get '/:slug', to: 'projects#show', as: 'projects_slug'
	get 'settings/withdraw/:id', to: 'settings#withdraw', as: 'withdraw'
	get 'users/show/:id', to: 'users#show', as: 'user_show'
	get 'projects/edit/:slug', to: 'projects#edit', as: 'edit_project'
	get 'rss_s3s/:hashid', to: 'rss_s3s#show', as: 'rss_s3'
	get 'rss_feeds/:hashid', to: 'rss_feeds#show', as: 'rss_feed', format: 'rss'

	resources :charges

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

	def withdraw
		@user = User.find(params[:id])
		@account = Stripe::Account.retrieve(current_user.accounts.first.stripe_infos.first.stripe_id)
		@stripe_id = current_user.accounts.first.stripe_infos.first.stripe_id
		@bank_accounts = Stripe::Account.retrieve(@stripe_id).external_accounts.data
		@account_balance = Stripe::Balance.retrieve(stripe_account: @account.id)

		@payout_list = Stripe::Payout.list({}, {:stripe_account => @account.id})

	end


	def user_params
		params.permit(:user_id)	# Will need to add `account` and `amount` to this
	end


end

app/views/settings/_accounts_section.html.erb
<div class="wd-accounts-section">
	<div class="w-container wd-accounts-container">
		<h3 class="wd-accounts-title">Accounts</h3>
		<table class="wd-accounts-table">
			<% @bank_accounts.each do |b| %>
			<tr>
				<td class="wd-accounts-table-tr"><%= '***' + b.last4 + ' ' + b.bank_name %></td>
				<td class="wd-accounts-table-tr">
					<% if b.default_for_currency == true %>
						<%= 'Default' %>
					<% else %>
						<%= link_to 'Set Default', stripe_infos_default_bank_account_path(id: b.id), method: :post, class: "link-to" %>
					<% end %>
				</td>
				<td class="wd-accounts-table-tr"><%= link_to 'Remove', stripe_infos_remove_bank_account_path(id: b.id), method: :post, class: "link-to" %></td>
			</tr>
			<% end %>
		</table>
		<a class="w-button wd-accounts-button" data-ix="add-bank-button" href="#">Add Account</a>
	</div>
</div>

app/views/settings/_add_bank_modal.html.erb
<div class="add-bank-modal" data-ix="add-bank-modal">
	<div class="add-bank-wrapper">
		<a class="add-bank-close">
			<strong class="add-bank-close-button" data-ix="add-bank-modal-close">X</strong>
		</a>
		<h3 class="add-bank-modal-title">Add Bank Account</h3>
		<p>Please submit your bank account details.</p>
		<div class="w-form">
			<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
			<form action="/stripe_infos/add_bank_account" method="POST" id="bank-account-form">
				<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

        <label class="form-label" for="routing-number">Routing Number</label>
        <input type="text" class="w-input routing-number" value="110000000"></input>

        <label class="form-label" for="account-number">Account Number</label>
        <input type="text" class="w-input account-number" value="000123456789"></input>

        <label class="form-label" for="account-holder-name">Account Holder Name</label>
        <input type="text" class="w-input account-holder-name" value="Jane Austen"></input>

        <label class="form-label" for="account-holder-type">Account Holder Type</label>
        <select class="w-input account-holder-type">
            <option value="individual">Individual</option>
            <option value="company">Company</option>
        </select>

		    <button type="submit" class="add-bank-button w-button">Submit</button>
			</form>

			<span class="payment-errors"></span>
			<span class="payment-success"></span>

			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>








<script>
	Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');

	function stripeResponseHandler(status, response) {
	    if (response.error) {
	        // re-enable the submit button
	        $('.submit-button').removeAttr("disabled");
	        // show the errors on the form
	        console.log(response.error);
	        $(".payment-success").html("");
	        $(".payment-errors").html(response.error.message);
	    } else {
	        var $form = $("#bank-account-form");
	        // token contains id, last4, and card type
	        var token = response['id'];
	        // insert the token into the form so it gets submitted to the server
	        $form.append("<input type='hidden' name='stripeToken' value='" + token + "' />");
	        // and submit
	        $form.get(0).submit();
	        // just for this example:
	        console.log(response);
	        // $(".payment-success").html(token);
	        // $(".payment-errors").html("");
	        // $('.submit-button').removeAttr("disabled");
	    }
	}

	$(document).ready(function () {
	    $("#bank-account-form").submit(function (event) {
	        // disable the submit button to prevent repeated clicks
	        $('.submit-button').attr("disabled", "disabled");
	        // bank account parameters
	        var bankAccountParams = {
	            country: 'US',	//Fixed-value for now
	            currency: 'USD',	//Fixed-value for now
	            //routing_number: $('.routing-number').val(),
	            account_number: $('.account-number').val(),
	        		account_holder_name: $('.account-holder-name').val(),
	            account_holder_type: $('.account-holder-type').val()
	        }
	        if ($('.routing-number').val() != '') {
	        	bankAccountParams['routing_number'] = $('.routing-number').val();
	        }
	        // createToken returns immediately - the supplied callback submits the form if there are no errors
	        Stripe.bankAccount.createToken(bankAccountParams, stripeResponseHandler);
	        // return false; // submit from callback
	    });
	});
</script>

app/views/settings/_fields_needed.html.erb
<div class="wd-withdraw-section">
	<div class="w-container wd-withdraw-container">
		<h3 class="wd-withdraw-title">Required Fields before withdrawal</h3>
		<div class="w-form">
			<form action="/stripe_infos/submit_fields_needed" method="POST">
				<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
				<% @account.verification.fields_needed.each do |field| %>
					<% if field == 'legal_entity.dob.day' %>
						<label class="wd-withdraw-label" for="dob">Date of Birth</label>
						<input type="date" name="dob" placeholder="mm/dd/yyyy" class="w-input wd-withdraw-textbox" data-name="dob" id="dob" required="required">
					<% elsif field == 'legal_entity.first_name' %>
						<label class="wd-withdraw-label" for="first_name">First Name</label>
						<input type="text" name="first_name" placeholder="First Name" class="w-input wd-withdraw-textbox" data-name="first_name" id="first_name" required="required">
					<% elsif field == 'legal_entity.last_name' %>
						<label class="wd-withdraw-label" for="last_name">Last Name</label>
						<input type="text" name="last_name" placeholder="First Name" class="w-input wd-withdraw-textbox" data-name="last_name" id="last_name" required="required">
					<% elsif field == 'legal_entity.type' %>
						<select class="w-select wd-withdraw-dropdown" data-name="entity_type" id="entity_type" name="entity_type" required="required">
								<option value="individual">Individual</option>
								<option value="business">Business</option>
						</select>
					<% elsif field == 'tos_acceptance.date' %>
						<label class="wd-withdraw-label" for="tos">Terms of Service</label>
						<div>
							<input type="checkbox" name="tos" data-name="tos" id="tos" required="required">
							<p style="display:inline-block;">By registering your account, you agree to our Services Agreement and the <a href="https://stripe.com/connect-account/legal">Stripe Connected Account Agreement.</a></p>
						</div>
					<% elsif field == 'legal_entity.address.line1' %>
						<label class="wd-withdraw-label" for="address_line">Address</label>
						<input type="text" name="address_line" placeholder="123 Fake St." class="w-input wd-withdraw-textbox" data-name="address_line" id="address_line" required="required">

					<% elsif field == 'legal_entity.address.postal_code' %>
						<label class="wd-withdraw-label" for="postal_code">Postal Code</label>
						<input type="text" name="postal_code" placeholder="90210" class="w-input wd-withdraw-textbox" data-name="postal_code" id="postal_code" required="required">

					<% elsif field == 'legal_entity.address.city' %>
						<label class="wd-withdraw-label" for="city">City</label>
						<input type="text" name="city" placeholder="Los Angeles" class="w-input wd-withdraw-textbox" data-name="city" id="city" required="required">

					<% elsif field == 'legal_entity.address.state' %>
						<label class="wd-withdraw-label" for="state">State</label>
						<input type="text" name="state" placeholder="CA" class="w-input wd-withdraw-textbox" data-name="state" id="state" required="required">

					<% elsif field == 'legal_entity.business_name' %>
						<label class="wd-withdraw-label" for="business_name">Business Name</label>
						<input type="text" name="business_name" placeholder="Business Name" class="w-input wd-withdraw-textbox" data-name="business_name" id="business_name" required="required">

					<% elsif field == 'legal_entity.business_tax_id' %>
						<label class="wd-withdraw-label" for="business_tax_id">Business Tax ID</label>
						<input type="text" name="business_tax_id" placeholder="Business Tax ID" class="w-input wd-withdraw-textbox" data-name="business_tax_id" id="business_tax_id" required="required">

					<% elsif field == 'legal_entity.ssn_last_4' %>
						<label class="wd-withdraw-label" for="ssn_last_4">Last 4 of SSN</label>
						<input type="text" name="ssn_last_4" placeholder="1234" class="w-input wd-withdraw-textbox" data-name="ssn_last_4" id="ssn_last_4" required="required">

					<% elsif field == 'legal_entity.personal_id_number' %>
						<label class="wd-withdraw-label" for="personal_id_number">Personal ID Number (SSN)</label>
						<input type="text" name="personal_id_number" placeholder="123-45-6789" class="w-input wd-withdraw-textbox" data-name="personal_id_number" id="personal_id_number" required="required">

					<% elsif field == 'legal_entity.verification.document' %>
						<label class="wd-withdraw-label" for="verification_document">Verification Document (contact Support)</label>
						<input type="text" name="verification_document" placeholder="Document" class="w-input wd-withdraw-textbox" data-name="verification_document" id="verification_document" required="required">
					<% end %>
				<% end %>
				<input class="w-button wd-withdraw-button" data-wait="Please wait..." type="submit" value="Submit">
			</form>
			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>

app/views/settings/_history_section.html.erb
<div class="wd-history-section">
	<div class="w-container wd-history-container">
		<h3 class="wd-history-title">Withdrawal History</h3>
		<table class="wd-history-table">
			<tr>
				<th class="wd-history-table-tr">Withdrawal Date</th>
				<th class="wd-history-table-tr">Completion Date</th>
				<th class="wd-history-table-tr">Account</th>
				<th class="wd-history-table-tr">Amount</th>
				<th class="wd-history-table-tr">Status</th>
			</tr>
			<% @payout_list.each do |p| %>
				<tr>
					<td class="wd-history-table-tr"><%= Time.zone.at(p.created).strftime("%B %d, %Y") %></td>
					<td class="wd-history-table-tr"><%= Time.zone.at(p.arrival_date).strftime("%B %d, %Y") %></td>
					<td class="wd-history-table-tr"><%= p.destination %></td><!-- TODO: Fix this to lookup BankAccount info using p.destination -->
					<td class="wd-history-table-tr">$<%= '%.2f' % (p.amount / 100.0) %> USD</td>
					<td class="wd-history-table-tr"><%= p.status %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/settings/_withdraw_section.html.erb
<div class="wd-withdraw-section">
	<div class="w-container wd-withdraw-container">
		<h3 class="wd-withdraw-title">Withdraw</h3>
		<label class="wd-withdraw-label">Current Balance</label>
		<p>
			$<%= '%.2f' % (@account_balance.available[0].amount / 100.0) %>
			<%= @account_balance.available[0].currency %>
		</p>
		<div class="w-form">
			<form action="/stripe_infos/create_payout" method="POST">
				<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

				<label class="wd-withdraw-label" for="account">Account</label>
				<select class="w-select wd-withdraw-dropdown" data-name="account" id="account" name="account">
					<% @bank_accounts.each do |b| %>
						<option value="<%= b.id %>"><%= '***' + b.last4 + ' ' + b.bank_name %></option>
					<% end %>
				</select>
				<label class="wd-withdraw-label" for="amount">Amount</label>
				<input class="w-input wd-withdraw-textbox" data-name="amount" id="amount" maxlength="16" name="amount" placeholder="0.00" required="required" type="text">
				<input class="w-button wd-withdraw-button" data-wait="Please wait..." type="submit" value="Withdraw">
			</form>
			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>

app/views/settings/add_bank_modal.html.erb
<div class="add-bank-modal" data-ix="add-bank-modal">
	<div class="add-bank-wrapper">
		<a class="add-bank-close">
			<strong class="add-bank-close-button" data-ix="add-bank-modal-close">X</strong>
		</a>
		<h3 class="add-bank-modal-title">Add Bank Account</h3>
		<p>Please submit your bank account details.</p>
		<div class="w-form">
			<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
			<form action="" method="POST" id="bank-account-form">

        <label class="form-label" for="routing-number">Routing Number</label>
        <input type="text" class="w-input" value="110000000" />

        <label class="form-label" for="account-number">Account Number</label>
        <input type="text" class="w-input" value="000123456789" />

        <label class="form-label" for="account-holder-name">Account Holder Name</label>
        <input type="text" class="w-input" value="Jane Austen" />

        <label class="form-label" for="account-holder-type">Account Holder Type</label>
        <select class="w-input">
            <option value="individual">Individual</option>
            <option value="company">Company</option>
        </select>

		    <button type="submit" class="submit-button">Submit</button>

			</form>
			<span class="payment-errors"></span>
			<span class="payment-success"></span>

			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>








<script>
	Stripe.setPublishableKey('<%= Rails.configuration.stripe.publishable_key %>');

	function stripeResponseHandler(status, response) {
	    if (response.error) {
	        // re-enable the submit button
	        $('.submit-button').removeAttr("disabled");
	        // show the errors on the form
	        console.log(response.error);
	        $(".payment-success").html("");
	        $(".payment-errors").html(response.error.message);
	    } else {
	        var $form = $("#bank-account-form");
	        // token contains id, last4, and card type
	        var token = response['id'];
	        // insert the token into the form so it gets submitted to the server
	        $form.append("<input type='hidden' name='stripeToken' value='" + token + "' />");
	        // and submit
	        //$form.get(0).submit();
	        // just for this example:
	        console.log(response);
	        $(".payment-success").html(token);
	        $(".payment-errors").html("");
	        $('.submit-button').removeAttr("disabled");
	    }
	}

	$(document).ready(function () {
	    $("#bank-account-form").submit(function (event) {
	        // disable the submit button to prevent repeated clicks
	        $('.submit-button').attr("disabled", "disabled");
	        // bank account parameters
	        var bankAccountParams = {
	            country: 'US',	//Fixed-value for now
	            currency: 'USD',	//Fixed-value for now
	            //routing_number: $('.routing-number').val(),
	            account_number: $('.account-number').val(),
	        		account_holder_name: $('.account-holder-name').val(),
	            account_holder_type: $('.account-holder-type').val()
	        }
	        if ($('.routing-number').val() != '') {
	        	bankAccountParams['routing_number'] = $('.routing-number').val();
	        }
	        // createToken returns immediately - the supplied callback submits the form if there are no errors
	        Stripe.bankAccount.createToken(bankAccountParams, stripeResponseHandler);
	        return false; // submit from callback
	    });
	});
</script>

app/views/settings/withdraw.html.erb
<body class="body-class">
	<%= render '/shared/signup_modal' %>
	<%= render '/shared/login_modal' %>
	<%= render '/shared/nav' %>
	<%= render '/settings/add_bank_modal' %>

	<% if current_user && current_user == @user %>

		<% if @account.verification.disabled_reason == 'fields_needed' %>
			<%= render '/settings/fields_needed' %>
		<% else %>
			<%= render '/settings/withdraw_section' %>
		<% end %>

		<%= render '/settings/accounts_section' %>

		<%= render '/settings/history_section' %>

	<% else %>
	You are not allowed to access this page
	<% end %>

</body>
<footer>
	<%= render '/shared/footer' %>
</footer>