config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "registrations"}
  get 'pages/landing'
	get 'pages/landing2'
  get 'projects/show/:id', to: 'projects#show', as: 'projects'
  get 'projects/index'
  get 'projects/new'
	post 'projects/create'
	post 'projects/update'
	post 'posts/create'
	post 'comments/create'
	post 'subscriptions/create'
	post 'stripe_infos/create'
	post 'stripe_infos/add_bank_account'
	post 'stripe_infos/remove_bank_account', to: 'stripe_infos#remove_bank_account', as: 'stripe_infos_remove_bank_account'
	post 'stripe_infos/default_bank_account', to: 'stripe_infos#default_bank_account', as: 'stripe_infos_default_bank_account'
	post 'stripe_infos/create_payout', to: 'stripe_infos#create_payout', as: 'stripe_infos_create_payout'
	post 'stripe_infos/submit_fields_needed', to: 'stripe_infos#submit_fields_needed', as: 'stripe_infos_submit_fields_needed'
	post 'stripe/webhooks', to: 'stripe_infos#stripe_webhooks', as: 'stripe_wehbooks'
	post 'releases/create'
	post 'rss_s3s/create'
	delete 'subscriptions/destroy/:id', to: 'subscriptions#destroy', as: 'subscriptions_destroy'
	get 'projects/dashboard/:id', to: 'projects#dashboard', as: 'dashboard'
	root to: 'pages#landing2'
	get '/:slug', to: 'projects#show', as: 'projects_slug'
	get 'settings/withdraw/:id', to: 'settings#withdraw', as: 'withdraw'
	get 'users/show/:id', to: 'users#show', as: 'user_show'
	get 'projects/edit/:slug', to: 'projects#edit', as: 'edit_project'
	get 'rss_s3s/:hashid', to: 'rss_s3s#show', as: 'rss_s3'
	get 'rss_feeds/:hashid', to: 'rss_feeds#show', as: 'rss_feed', format: 'rss'

	resources :charges

end

app/models/project.rb
class Project < ActiveRecord::Base
	# obfuscate_id :spin => 72894092
  belongs_to :user
	has_many :subscriptions,  dependent: :destroy
	has_many :posts,  dependent: :destroy
	has_many :comments,  dependent: :destroy
	has_many :rewards_tiers,  dependent: :destroy
	has_many :goals,  dependent: :destroy
	has_many :transaction_queues
	has_many :releases
	has_many :past_transactions
	delegate :monthly_subscriptions, :release_subscriptions, to: :subscriptions
	delegate :monthly_transaction_queues, :release_transaction_queues, to: :transaction_queues
	accepts_nested_attributes_for :rewards_tiers
	accepts_nested_attributes_for :goals
	has_attached_file :box_image, styles: { original: "300x300#", medium: "300x300#", thumb: "100x100#" }, default_url: "/assets/:style/missing.png"
 	validates_attachment_content_type :box_image, content_type: /\Aimage\/.*\z/
	# URL Slug creation
	before_save :assign_slug

	def amount_sum
		Subscription.where(project_id: self.id).sum(:amount)
	end

	def self.search(search)
  	where("title ILIKE ? OR body ILIKE ?", "%#{search}%", "%#{search}%")
	end

	private

	# Create url slug
	def assign_slug
		if Project.where(slug: title.parameterize('')).exists?
			self.slug = title.parameterize('') + Random.rand(999).to_s
		else
			self.slug = title.parameterize('')
 		end
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def show
		if params[:id]
			@project = Project.find(params[:id])
		else
			@project = Project.find_by(slug: params[:slug])
		end
		@post = @project.posts.build
		@rss_s3 = @post.build_rss_s3
  end

  def index
		if params[:search]
			@projects = Project.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
		else
			@projects = Project.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 4)
		end
  end

	def new
    @project = Project.new
		@project.rewards_tiers.build
		@project.goals.build
  end

	def edit
		if params[:id]
			@project = Project.find(params[:id])
		else
			@project = Project.find_by(slug: params[:slug])
		end
	end

	def update
		if params[:id]
			@project = Project.find(params[:id])
		else
			@project = Project.find_by(slug: params[:slug])
		end
	  if @project.update_attributes(project_params)
	    flash[:notice] = 'Profile was successfully updated.'
	    redirect_to(projects_slug_path(@project.slug))
	  else
	    render "edit"
	  end
	end

  def create
    @project = Project.new project_params
		# If User does not have Stripe account_id, create one
		@account = Account.where(user_id: @project.user.id).first
		unless @account
			# Create a User.Account
			Account.create(user_id: current_user.id)
			@account = Account.where(user_id: @project.user.id).first
		end
		unless @account && StripeInfo.where(account_id: @account.id).first
			# Create StripeInfo record
			StripeInfo.create(account_id: @account.id)
		end
		unless @account && StripeInfo.where(account_id: @account.id).first.stripe_id
			# Create Managed Stripe Account
			stripe_account = Stripe::Account.create(
			  {
			    :country => @project.user.country.code, #"US",
			    :managed => true
			  }
			)
			stripe_info = StripeInfo.where(account_id: @account.id).first
			stripe_info.stripe_id = stripe_account.id
			stripe_info.secret_key = stripe_account.keys.secret
			stripe_info.publishable_key = stripe_account.keys.publishable
			stripe_info.save

			# Accept TOS (accepted on sign_up)
			stripe_account.tos_acceptance.date = Time.now.to_i
			stripe_account.tos_acceptance.ip = request.remote_ip
			stripe_account.save

		end

    if @project.save
      redirect_to projects_path(@project)#, notice: "Project succesfully created"
    else
      render :action => 'new'
    end
  end

	def dashboard
		@project = Project.find(params[:id])
		@account = Account.where(user_id: @project.user.id).first

		# Create variables to use as data in Dashboard charts
		@earnings_over_time = PastTransaction.where(project_id: @project.id).group_by_month(:created_at, last: 6).sum(:amount)
		@subscriptions_over_time = PastTransaction.where(project_id: @project.id).group_by_month(:created_at, last: 6).count
		@posts_over_time = Post.where(project_id: @project.id).group_by_month(:created_at, last: 6).count
		@comments_over_time = Comment.where(project_id: @project.id).group_by_month(:created_at, last: 6).count
		@number_charges_declined = PastTransaction.where(project_id: @project.id).where(status: 'failed').group_by_month(:created_at, last: 6).count
		@number_charges_accepted = PastTransaction.where(project_id: @project.id).where(status: 'successful').group_by_month(:created_at, last: 6).count
		# Format dates for column_chart
		@number_charges_declined = @number_charges_declined.transform_keys.with_index{ |key, i| if i % 2 == 0 then key.strftime("%b %Y") else " "*i end }
		@number_charges_accepted = @number_charges_accepted.transform_keys.with_index{ |key, i| if i % 2 == 0 then key.strftime("%b %Y") else " "*i end }

		# @amount_charges_declined = PastTransaction.where(project_id: @project.id).where(status: 'failed').group_by_month(:created_at, last: 6).sum(:amount)
		# @amount_charges_accepted = PastTransaction.where(project_id: @project.id).where(status: 'successful').group_by_month(:created_at, last: 6).sum(:amount)

		# Find Stripe account balance
		@account_balance = Stripe::Balance.retrieve(stripe_account: StripeInfo.where(account_id: @account.id).first.stripe_id)

	end

	private

	def project_params
		params.require(:project).permit(:user_id, :title, :format, :charge_occurrence, :body, :box_image, rewards_tiers_attributes: [:min_amount, :body], goals_attributes: [:amount, :body])
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_card_modal.html.erb
<div class="stripe-info-modal" data-ix="stripe-info-modal">
	<div class="stripe-info-wrapper">
		<a class="stripe-info-close">
			<strong class="stripe-info-close-button" data-ix="stripe-info-modal-close">X</strong>
		</a>
		<h3 class="stripe-info-modal-title">Subscribe</h3>
		<p>Please choose your subscription.</p>
		<div class="w-form">
			<%= form_tag stripe_infos_create_path do %>
			  <article>
			    <% if flash[:error].present? %>
			      <div id="error_explanation">
			        <p><%= flash[:error] %></p>
			      </div>
			    <% end %>
			  </article>

			  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
			          data-email=<%= current_user.email %>
			          data-locale="auto"></script>
			<% end %>
			<div class="w-form-done">
				<div>Thank you! Your submission has been received!</div>
			</div>
			<div class="w-form-fail">
				<div>Oops! Something went wrong while submitting the form</div>
			</div>
		</div>
	</div>
</div>

app/views/projects/_comment_div.html.erb
<div class="comment-div">
	<div class="w-row">
		<div class="comment-profile w-col w-col-2"><img src="<%= c.user.avatar %>" width="64">
		</div>
		<div class="w-col w-col-10">
			<h5 class="comment-name"><%= c.user.username %></h5>
			<p class="comment-time"><%= time_ago_in_words(c.created_at) %> ago</p>
			<p><%= c.body %></p>
		</div>
	</div>
</div>

app/views/projects/_comment_form.html.erb
<%= form_for :comment, url: {controller: "comments", action: "create"} do |p| %>
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<%= p.hidden_field :project_id, :value => @project.id %>
	<%= p.hidden_field :user_id, :value => current_user.id %>

	<label for="body">Body</label>
	<%= p.text_area :body, data: {name: 'body'}, class: "w-input", id: "body", maxlength: "5000", placeholder: "Leave a comment..", required: "required", autofocus: 'true' %>
	<input class="submit-project-button w-button" data-wait="Please wait..." type="submit" value="Comment"><a class="cancel-button w-button" href="#">Cancel</a>
<% end %>

app/views/projects/_goal_form.html.erb
<div class="tier-creation-div">
	<script>
		document.getElementById("goals-creation-div").lastElementChild.insertAdjacentHTML('beforeend','<label for="amount">Goal Amount</label>');
		document.getElementById("goals-creation-div").lastElementChild.insertAdjacentHTML('beforeend','<input data-name="amount" class="w-input" id="amount" maxlength="256" placeholder="$100" required="required" autofocus="autofocus" size="256" type="text" name="project[goals_attributes]['+goals_tier_index+'][amount]">');
		document.getElementById("goals-creation-div").lastElementChild.insertAdjacentHTML('beforeend','<label for="body">Goal Body</label>');
		document.getElementById("goals-creation-div").lastElementChild.insertAdjacentHTML('beforeend', '<textarea data-name="body" class="w-input" id="body" maxlength="5000" placeholder="We do two shows a week..." required="required" autofocus="autofocus" name="project[goals_attributes]['+goals_tier_index+'][body]"></textarea>');
	</script>
</div>

app/views/projects/_pledge_div.html.erb
<div class="pledge-div">
	<h4 class="pledge-title"><%= r.title %></h4>
	<h6 class="patron-count"><%= Subscription.where(rewards_tier_id: r.id).count %> Backers</h6>
	<%= r.body %>
	<div class="button-block">
		<!-- If user is signed in and is subscribed at this rewards_tier level -->
		<% if current_user && Subscription.exists?(user_id: current_user, project_id: @project.id, rewards_tier_id: r.id) %>
			<a style="background-color:#c1c1c1;" class="pledge-button w-button" data-ix="subscribe-button" href="#">Pledge <%= number_to_currency(r.min_amount, :unit => "$", :precision => 0) %></a>
			<%= link_to 'Cancel Subscription', subscriptions_destroy_path(Subscription.where(user_id: current_user, project_id: @project.id, rewards_tier_id: r.id).first.id), method: 'delete', confirm: "Are you sure ?", class: 'cancel-subscribe-text' %>
		<% else %>
			<a class="pledge-button w-button" data-ix="login-button" href="#">Pledge <%= number_to_currency(r.min_amount, :unit => "$", :precision => 0) %></a>
		<% end %>
	</div>
</div>

app/views/projects/_post_form.html.erb
<%= form_for @post, url: {controller: "posts", action: "create"} do |p| %>
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<%= p.hidden_field :project_id, :value => @project.id %>
	<label for="title">Title</label>
	<%= p.text_field :title, data: {name: 'title'}, class: "w-input", id: "title", maxlength: "256", placeholder: "Post Title", required: "required",  autofocus: 'true' %>

	<%= p.fields_for @rss_s3 do |r| %>
		<label for="box_image">RSS File</label>
		<%= r.file_field :file, class: "w-input", id: "box-image" %>
	<% end %>

	<label for="body">Body</label>
	<%= p.trix_editor :body %>
	<br>
	<input class="submit-project-button w-button" data-wait="Please wait..." type="submit" value="Create Post">
	<a class="cancel-button w-button" href="#">Cancel</a>
<% end %>

app/views/projects/_rewards_tier_form.html.erb
<div class="tier-creation-div">
	<script>
		document.getElementById("rewards-creation-div").lastElementChild.insertAdjacentHTML('beforeend','<label for="min_amount">Tier Amount</label>');
		document.getElementById("rewards-creation-div").lastElementChild.insertAdjacentHTML('beforeend','<input data-name="min_amount" class="w-input" id="min_amount" maxlength="256" placeholder="$1" required="required" autofocus="autofocus" size="256" type="text" name="project[rewards_tiers_attributes]['+rewards_tier_index+'][min_amount]">');
		document.getElementById("rewards-creation-div").lastElementChild.insertAdjacentHTML('beforeend','<label for="body">Tier Body</label>');
		document.getElementById("rewards-creation-div").lastElementChild.insertAdjacentHTML('beforeend', '<textarea data-name="body" class="w-input" id="body" maxlength="5000" placeholder="We email you the show notes and links..." required="required" autofocus="autofocus" name="project[rewards_tiers_attributes]['+rewards_tier_index+'][body]"></textarea>');
	</script>
</div>

app/views/projects/_subscribe_modal.html.erb
<!-- If the user has a card on file, let them subscribe. Else charge them for first time -->
<div class="subscribe-modal" data-ix="subscribe-modal">
	<div class="subscribe-wrapper">
		<a class="subscribe-close">
			<strong class="subscribe-close-button" data-ix="subscribe-modal-close">X</strong>
		</a>

		<% if current_user && StripeInfo.where(account_id: current_user.accounts.select(:id)).present? %>
			<h3 class="subscribe-modal-title">Subscribe</h3>
			<p>Please choose your subscription.</p>
			<div class="w-form">
				<%= form_for('subscription', data: {name: "subscription Form"}, html: {id: "subscription-form", name: "subscription-form"}, url: subscriptions_create_path ) do |f| %>
					<%= f.hidden_field :user_id, value: current_user.id %>
					<%= f.hidden_field :project_id, value: @project.id %>
					<%= f.hidden_field :type, :value => @project.charge_occurrence %>
					<label class="form-label" for="tier">Tier</label>
					<select data-name="rewards-tier-id" class="w-input" id="rewards-tier-id" maxlength="256" required="required" name="subscription[rewards_tier_id]"><option value=""></option>
						<% @project.rewards_tiers.each do |rt| %>
							<option value="<%= rt.id %>" <%= 'disabled' if Subscription.exists?(user_id: current_user, project_id: @project.id, rewards_tier_id: rt.id) %>><%= rt.title %></option>
						<% end %>
					</select>

					<label class="form-label" for="amount">Amount</label>
					<%= f.text_field :amount, data: {name: 'amount'}, class: "w-input", id: "amount", maxlength: "256", placeholder: "$1", required: "required" %>

					<%= f.submit "Subscribe", class: 'subscribe-button w-button', data: {wait: 'Please wait...'} %>
				<% end %>
				<div class="w-form-done">
					<div>Thank you! Your submission has been received!</div>
				</div>
				<div class="w-form-fail">
					<div>Oops! Something went wrong while submitting the form</div>
				</div>
			</div>
		<% elsif current_user %>
			<h3 class="stripe-info-modal-title">Add Card</h3>
			<p>Please add your card.</p>
			<% if @project.charge_occurrence = "MonthlySubscription" %>
				<p>You will be changed at the end of every month.</p>
			<% else %>
				<p>You will be changed at the time of each project release.</p>
			<% end %>
			<p>After saving your card you can subscribe from the project page.</p>
			<div class="w-form">
				<article>
					<% if flash[:error].present? %>
						<div id="error_explanation">
							<p><%= flash[:error] %></p>
						</div>
					<% end %>
				</article>

				<%= form_tag stripe_infos_create_path do %>
				  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
				          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
				          data-email="<%= current_user.email %>"
				          data-locale="auto"
									data-zip-code="true"
									data-allow-remember-me="false"></script>
				<% end %>
				<div class="w-form-done">
					<div>Thank you! Your submission has been received!</div>
				</div>
				<div class="w-form-fail">
					<div>Oops! Something went wrong while submitting the form</div>
				</div>
			</div>

		<% end %>


	</div>
</div>

app/views/projects/dashboard.html.erb
<body class="body-class">
	<%= render '/shared/signup_modal' %>
	<%= render '/shared/login_modal' %>
	<%= render '/shared/nav' %>
	<% if current_user && current_user == @project.user %>
	  <div class="dashboard-section">
	    <div class="w-container">
	      <h1 class="dashboard-h1">Dashboard</h1>
				<h4 class="dashboard-project-name">for <%= @project.title %></h4>
				<div class="dashboard-div-account-balance">
					<h6 class="dashboard-account-balance">Account Balance:
						$<%= '%.2f' % (@account_balance.available[0].amount / 100.0) %>
						<%= @account_balance.available[0].currency %>
					</h6><a class="dashboard-withdraw-button w-button" href="<%= withdraw_path(current_user.id) %>">Withdraw</a>
				</div>
	      <div class="w-row">
	        <div class="w-col w-col-6">
	          <div class="dashboard-graph-block">
							<h5 class="dashboard-graph-title">Earnings over Time<h5>
							<%= line_chart @earnings_over_time, xtitle: "Date", ytitle: "Earnings" %>
	          </div>
	          <div class="dashboard-graph-block">
							<h5 class="dashboard-graph-title">Subscriptions over Time<h5>
							<%= line_chart @subscriptions_over_time, xtitle: "Date", ytitle: "Subscriptions" %>
	          </div>
	        </div>
	        <div class="w-col w-col-6">
	          <div class="dashboard-graph-block">
							<h5 class="dashboard-graph-title">Engagement over Time<h5>
							<%= line_chart [
								{name: "Posts", data: @posts_over_time },
								{name: "Comments", data: @comments_over_time }
								],
								xtitle: "Date",
								ytitle: "Engagement"
							%>
	          </div>
	          <div class="dashboard-graph-block">
							<h5 class="dashboard-graph-title">Charges over Time<h5>
							<%= column_chart [
								{name: "Accepted", data: @number_charges_accepted },
								{name: "Declined", data: @number_charges_declined }
								],
								stacked: true,
								xtitle: "Date",
								ytitle: "Transactions",
								library: {
									format: 'MM/YY'
								},
								discrete: true
							%>
	          </div>
	        </div>
	      </div>
				<div class="w-embed dashboard-cust-div">
					<table class="dashboard-cust-table">
						<tr>
							<th class="dashboard-cust-table-th">Customer</th>
							<th class="dashboard-cust-table-th">Pledge</th>
							<th class="dashboard-cust-table-th">Rewards Tier</th>
						</tr>
						<% Subscription.where(project_id: @project.id).each do |s| %>
							<tr>
								<td class="dashboard-cust-table-th"><%= s.user.username %></td>
								<td class="dashboard-cust-table-th">$<%= s.amount.to_i %></td>
								<td class="dashboard-cust-table-th"><%= s.rewards_tier.title %></td>
							</tr>
						<% end %>
					</table>
				</div>
	    </div>
	  </div>
	<% else %>
		You are not allowed to access this page
	<% end %>
</body>
<footer>
	<%= render '/shared/footer' %>
</footer>

app/views/projects/show.html.erb
<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com -->
<!--  Last Published: Tue Feb 14 2017 00:27:56 GMT+0000 (UTC)  -->
<html data-wf-page="589bc50215395b8d57bc1cb1" data-wf-site="589bc50215395b8d57bc1cb0">
<head>
  <meta charset="utf-8">
  <title>Adam&#39;s Top-Notch Site</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script type="text/javascript">
    WebFont.load({
      google: {
        families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic"]
      }
    });
  </script></script>
</head>
<body class="body-class">
	<%= render '/shared/signup_modal' %>
	<%= render '/shared/login_modal' %>
	<%= render '/shared/nav' %>
	<%= render 'subscribe_modal' %>
  <div class="header-section">
    <div class="w-container">
      <h1 class="main-title">Contribute to <%= @project.title %></h1>
      <div class="w-row">
        <div class="w-col w-col-7">
          <div class="header-image"><img class="main-img" height="300" src="<%= @project.box_image.url(:medium) %>" width="300">
          </div>
        </div>
        <div class="summary-col w-col w-col-5">
          <div class="summary-stats">
            <h1 class="summary-h1"><%= @project.subscriptions.count %></h1>
            <h5 class="summary-h6">backers</h5>
            <h1 class="summary-h1"><%= number_to_currency(@project.amount_sum, :unit => "$", precision: 0) %></h1>
            <h5 class="summary-h6">per episode</h5>
            <div class="w-clearfix"><a class="support-button w-button" data-ix="<%= if current_user then 'subscribe-button' else 'login-button' end %>" href="#">Support Project</a><a class="share-button w-button" href="#">Share</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div>
    <div class="w-tabs" data-duration-in="300" data-duration-out="100">
      <div class="main-tabs-menu w-tab-menu">
        <a class="main-tab-link w--current w-inline-block w-tab-link" data-w-tab="overview">
          <div>Overview</div>
        </a>
        <a class="main-tab-link w-inline-block w-tab-link" data-w-tab="posts">
          <div>Posts</div>
        </a>
        <a class="main-tab-link w-inline-block w-tab-link" data-w-tab="comments">
          <div>Comments</div>
        </a>
      </div>
      <div class="tab-pane w-tab-content">
        <div class="body-class w--tab-active w-tab-pane" data-w-tab="overview">
          <div class="tab-div">
            <div class="w-row">
              <div class="w-col w-col-1"></div>
              <div class="w-col w-col-7">
								<% if user_signed_in? && current_user.id == @project.user_id %>
									<%= link_to 'View Dashboard', dashboard_path(@project), class: 'create-release-text' %>
                  <%= link_to 'Edit Project', edit_project_path(@project.slug), class: 'create-release-text' %>
									<% if @project.charge_occurrence == "ReleaseSubscription" %>
										<%= link_to 'Create Release', releases_create_path(project_id: @project.id), method: 'post', class: 'create-release-text', confirm: "Are you sure ?" %>
									<% end %>

                  <!-- <%= form_for @rss_s3, url: {controller: "rss_s3s", action: "create"} do |f| %>
                  <%= f.hidden_field :project_id, :value => @project.id %>
                  <label for="box_image">RSS File</label>
                  <%= f.file_field :file, class: "w-input", id: "box-image" %>
                  <input class="submit-project-button w-button" data-wait="Please wait..." type="submit" value="Post to RSS Feed">
                  <% end %> -->

								<% end %>
                <h1><%= @project.title %></h1>
                <%= @project.body.html_safe %>
							</div>
              <div class="w-col w-col-3">
                <div class="rewards-div">
                  <h5 class="rewards-title">Rewards</h5>
									<% @project.rewards_tiers.each do |r| %>
										<%= render 'pledge_div', r: r %>
									<% end %>
                </div>
              </div>
              <div class="w-col w-col-1"></div>
            </div>
          </div>
        </div>
        <div class="w-tab-pane" data-w-tab="posts">
          <div class="tab-div">
            <div class="w-row">
              <div class="w-col w-col-1"></div>
              <div class="w-col w-col-7">
								<% if user_signed_in? && current_user.id == @project.user_id %>
									<%= render 'post_form' %>
								<% end %>
								<% @project.posts.order("created_at desc").each do |post| %>
									<h1 class="project-post-title"><%= post.title %></h1>
									<p class="comment-time"><%= time_ago_in_words(post.created_at) %> ago</p>
									<p><%= post.body.html_safe %></p>
								<% end %>
							</div>
              <div class="w-col w-col-3">
                <div class="rewards-div">
                  <h5 class="rewards-title">Rewards</h5>
                  <div class="pledge-div">
										<% @project.rewards_tiers.each do |r| %>
											<%= render 'pledge_div', r: r %>
										<% end %>
									</div>
              	</div>
	            </div>
            <div class="w-col w-col-1"></div>
          </div>
        </div>
			</div>
        <div class="w-tab-pane" data-w-tab="comments">
          <div class="tab-div">
            <div class="w-row">
              <div class="w-col w-col-1"></div>
              <div class="w-col w-col-7">
                <div class="leave-comment">
                  <h4 class="comments-title">Leave a comment</h4>
									<% if user_signed_in? %>
										<%= render 'comment_form' %>
									<% else %>
	                  <p class="comment-text">Please sign in to leave a comment</p>
									<% end %>
                </div>
                <div class="comment-container w-container">
									<% @project.comments.order("created_at desc").each do |c| %>
										<%= render 'comment_div', c: c %>
									<% end %>
                </div>
              </div>
              <div class="w-col w-col-3">
                <div class="rewards-div">
                  <h5 class="rewards-title">Rewards</h5>
									<% @project.rewards_tiers.each do |r| %>
										<%= render 'pledge_div', r: r %>
									<% end %>
                </div>
              </div>
              <div class="w-col w-col-1"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js" type="text/javascript"></script>

  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>

<footer>
	<%= render '/shared/footer' %>
</footer>
<script>
Webflow.push(function() {
  $('.w-tab-link').each(function() {
    $(this).attr('href', '#' + $(this).attr('data-w-tab').toLowerCase().replace(/[^a-z0-9]+/, '-'));
  });
  if(location.hash != '') $('.w-tab-link[href="'+location.hash+'"]')[0].click();
});
</script>
</html>